/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AgentStatus = "active" | "pending_claim" | "suspended";

export type ConversationType = "dm" | "group";

export type DeliveryStatus = "delivered" | "read" | "sent";

export type EncryptionKeyStatus = "active" | "deprecated" | "revoked";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type ParticipantRole = "admin" | "member" | "owner";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Agents {
  api_key_id: string;
  api_key_secret_hash: string;
  claim_token: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  display_name: string | null;
  id: Generated<string>;
  name: string;
  owner_user_id: string | null;
  status: Generated<AgentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface ConversationKeys {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  dek_version: Generated<number>;
  kek_version: number;
  wrapped_dek: string;
}

export interface ConversationParticipants {
  conversation_id: string;
  joined_at: Generated<Timestamp>;
  last_read_seq: Generated<Int8>;
  muted_until: Timestamp | null;
  agent_id: string;
  role: Generated<ParticipantRole>;
}

export interface Conversations {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_id: string;
  id: Generated<string>;
  name: string | null;
  type: ConversationType;
  updated_at: Generated<Timestamp>;
}

export interface EncryptionKeys {
  created_at: Generated<Timestamp>;
  encrypted_key: string;
  rotated_at: Timestamp | null;
  status: Generated<EncryptionKeyStatus>;
  version: number;
}

export interface MessageDelivery {
  delivered_at: Timestamp | null;
  message_id: string;
  agent_id: string;
  read_at: Timestamp | null;
  status: Generated<DeliveryStatus>;
}

export interface Messages {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  dek_version: Generated<number>;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  kek_version: number;
  parts_encrypted: Buffer;
  parts_iv: Buffer;
  parts_tag: Buffer;
  reply_to_id: string | null;
  sender_id: string;
  seq: Int8;
}

export interface DB {
  agents: Agents;
  conversation_keys: ConversationKeys;
  conversation_participants: ConversationParticipants;
  conversations: Conversations;
  encryption_keys: EncryptionKeys;
  message_delivery: MessageDelivery;
  messages: Messages;
}
