/** @file Package-private facade for the complete Client protocol representation. */
// safer-arch-ignore no-inventory-barrel: This is the complete protocol-representation facade; its sibling modules are the parts of one closed representation.

/* eslint-disable jsdoc/require-jsdoc -- Re-exported private symbols retain their owning-module documentation. */

export {
  ClientRepresentationError,
  decodeCanonical,
  type DecodedOuterBody,
  decodeOuterBody,
  deriveConversationId,
  deriveEvidenceMessageId,
  encodeCanonical,
  equalCanonical,
  hashAction,
  hashAnchor,
  hashMembershipDescriptor,
  hashPostIntent,
  hashRecord,
  mintPostId,
  type OuterMembership,
  sameBytes,
  signEvidenceMessage,
  signOuterEvidence,
  signOuterPacket,
} from "./encoding/index.js";
export {
  ActionCertificate,
  ActionCertifiedRecord,
  ActionCore,
  ActionHash,
  ActionProposal,
  ActionSignatureStatement,
  AnchorBody,
  AnchorHash,
  canonicalIdentifier,
  CatchUpAttestationStatement,
  CatchUpIncomplete,
  CatchUpItem,
  CatchUpPage,
  CatchUpRequest,
  CertifiedRecord,
  CompletedReanchor,
  ConversationId,
  ConversationIdentityInput,
  DirectPacket,
  DurabilityCertificate,
  DurabilityVoteStatement,
  EvidenceStatement,
  GenesisActionCore,
  GenesisAnchorBody,
  MembershipDescriptor,
  MembershipHash,
  PostActionCore,
  PostIntent,
  PostIntentHash,
  ReanchorBody,
  ReanchorCertificate,
  ReanchorVoteStatement,
  RecordCore,
  RecordHash,
  RouterAnchor,
} from "./schemas.js";
export {
  AgentAddress,
  compareAgentIds,
  Content,
  ContentPart,
  exactStruct,
  GroupAddress,
  isCanonicalIdentifier,
  JsonValue,
  maximumContentBytes,
  maximumMembers,
  MessageAddressInput,
  PostId,
  wellFormedString,
} from "./values.js";

export {
  memberCard,
  quorumThreshold,
  type VerifiedActionCertifiedRecord,
  type VerifiedActionCore,
  type VerifiedEvidence,
  type VerifiedMembership,
  type VerifiedRecordCore,
  verifyActionCertificate,
  verifyActionCertifiedRecord,
  verifyActionCore,
  verifyActionProposal,
  verifyCatchUpIncomplete,
  verifyCatchUpPage,
  verifyCertifiedRecord,
  verifyCompletedReanchor,
  verifyMembershipDescriptor,
  verifyOuterMessage,
  verifyRecordCore,
  verifyStableEvidence,
} from "./verification.js";

/* eslint-enable jsdoc/require-jsdoc -- Restore package documentation rules. */
