#!/usr/bin/env tsx
/**
 * @file Bakes `docs/snippets/ws-connect-example.mdx` — the
 * `agent/network/connect` request plus its HelloOk response — from the live
 * `PROTOCOL_VERSION` and `API_KEY_PREFIX` constants.
 *
 * Hook into `pnpm docs:generate`; `pnpm docs:check:drift` then catches any
 * drift between those constants and the generated file.
 *
 * Drift-resistance: re-running is idempotent (deterministic source data →
 * deterministic MDX). The doc pipeline diffs the working tree after running;
 * non-zero diff fails CI.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  readPackageVersion,
  readTopLevelStringConst,
  type ReadResult,
} from "./docs-generator.helpers.js";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const workspaceRoot = resolve(scriptDir, "..", "..", "..");
const snippetsDir = resolve(workspaceRoot, "docs", "snippets");

const AUTO_GEN_NOTE =
  "{/* AUTO-GENERATED by packages/client/scripts/generate-ws-connect-snippet.ts. " +
  "Do not edit by hand — re-run `pnpm docs:generate`. */}";

/**
 * Read `PROTOCOL_VERSION` from the protocol package manifest, which is the
 * single source of truth for both package and wire versions. Reading JSON
 * keeps the generator decoupled from the protocol package's build output.
 * @returns The protocol version or a typed source error.
 */
const readProtocolVersion = (): ReadResult<string> => {
  const sourcePath = resolve(workspaceRoot, "packages/protocol/package.json");
  const result = readPackageVersion(readFileSync(sourcePath, "utf8"));
  if (result._tag === "err") {
    return {
      _tag: "err",
      reason: `generate-ws-connect-snippet: ${result.reason} in ${sourcePath}`,
    };
  }
  return result;
};

/**
 * Read `API_KEY_PREFIX` from
 * `packages/server/src/identity/credential-keys.ts`. The generated snippet
 * uses the live prefix instead of a hardcoded `"moltzap_agent_"` so it
 * survives any future prefix change.
 * @returns The API key prefix or a typed source error.
 */
const readApiKeyPrefix = (): ReadResult<string> => {
  const sourcePath = resolve(
    workspaceRoot,
    "packages/server/src/identity/credential-keys.ts",
  );
  const result = readTopLevelStringConst(
    readFileSync(sourcePath, "utf8"),
    "API_KEY_PREFIX",
  );
  if (result._tag === "err") {
    return {
      _tag: "err",
      reason: `generate-ws-connect-snippet: ${result.reason} in ${sourcePath}`,
    };
  }
  return result;
};

interface SnippetInputs {
  readonly protocolVersion: string;
  readonly apiKeyPrefix: string;
}

const renderWsConnectSnippet = ({
  protocolVersion,
  apiKeyPrefix,
}: SnippetInputs): string => {
  // The HelloOk is empty: success is the only signal. The handshake sends a
  // single prefixed `agentKey`; the server resolves the principal off the
  // prefix and replies with `{ }` on success.
  const json = JSON.stringify({ jsonrpc: "2.0", id: "1", result: {} }, null, 2);
  const request = JSON.stringify(
    {
      jsonrpc: "2.0",
      id: "1",
      method: "agent/network/connect",
      params: {
        agentKey: `${apiKeyPrefix}abc123...`,
        minProtocol: protocolVersion,
        maxProtocol: protocolVersion,
      },
    },
    null,
    2,
  );
  // Marker exempts the file from the constants gate for these
  // generator-managed literals (`apiKeyPrefix` + `protocolVersion` inside
  // fenced JSON, where MDX cannot evaluate JSX). Drift gate catches via
  // git-diff after regen.
  return [
    AUTO_GEN_NOTE,
    "{/* @bake-constants: API_KEY_PREFIX PROTOCOL_VERSION */}",
    "",
    "<Tabs>",
    '  <Tab title="Request">',
    "    ```json",
    ...request.split("\n").map((l) => `    ${l}`),
    "    ```",
    "  </Tab>",
    '  <Tab title="Response (HelloOk)">',
    "    ```json",
    ...json.split("\n").map((l) => `    ${l}`),
    "    ```",
    "  </Tab>",
    "</Tabs>",
    "",
  ].join("\n");
};

const main = (): void => {
  mkdirSync(snippetsDir, { recursive: true });

  const protocolVersion = readProtocolVersion();
  const apiKeyPrefix = readApiKeyPrefix();
  if (protocolVersion._tag === "err") {
    console.error(protocolVersion.reason);
    process.exit(1);
  }
  if (apiKeyPrefix._tag === "err") {
    console.error(apiKeyPrefix.reason);
    process.exit(1);
  }
  writeFileSync(
    resolve(snippetsDir, "ws-connect-example.mdx"),
    renderWsConnectSnippet({
      protocolVersion: protocolVersion.value,
      apiKeyPrefix: apiKeyPrefix.value,
    }),
  );

  console.log(
    `[generate-ws-connect-snippet] wrote connect snippet (PROTOCOL_VERSION=${protocolVersion.value})`,
  );
};

main();
