/**
 * @file Public barrel for task, conversation, message, and task-manager protocol descriptors.
 */
export type { ConversationId, MessageId, TaskId } from "./methods.js";

export {
  TaskClosedError,
  ConversationArchivedError,
  ConversationFullError,
  HookBlockedError,
  ConversationsCreate,
  ConversationsList,
  ConversationsGet,
  ConversationsUpdate,
  ConversationsMute,
  ConversationsUnmute,
  ConversationsAddParticipant,
  ConversationsRemoveParticipant,
  ConversationsLeave,
  ConversationsArchive,
  ConversationsUnarchive,
  MessagesSend,
  MessagesList,
  TasksCreate,
  TasksGet,
  TasksList,
  TasksClose,
  TasksCreateConversation,
  TasksCloseConversation,
  TasksAddParticipant,
  TasksRemoveParticipant,
  TasksStoreMessage,
  TasksGetMessages,
  TasksGetMessagesSince,
  ConversationCreatedNotificationDefinition,
  ConversationUpdatedNotificationDefinition,
  ConversationArchivedNotificationDefinition,
  ConversationUnarchivedNotificationDefinition,
  ParticipantsAddedNotificationDefinition,
  ParticipantsRemovedNotificationDefinition,
  MessageReceivedNotificationDefinition,
  TaskClosedNotificationDefinition,
  TaskFailedNotificationDefinition,
  validateTmDecision,
  tmDecisionSchema,
  messageWithTmDecisionSchema,
} from "./methods.js";

export type {
  LogicalClock,
  Part,
  Message,
  Conversation,
  ConversationParticipant,
  ConversationSummary,
  TaskStatus,
  Task,
  TaskParticipant,
  TmType,
  ConversationCreatedNotification,
  ConversationUpdatedNotification,
  ConversationArchivedNotification,
  ConversationUnarchivedNotification,
  ParticipantsAddedNotification,
  ParticipantsRemovedNotification,
  MessageReceivedNotification,
  TmDecision,
  MessageWithTmDecision,
} from "./methods.js";
