/**
 * @file Public barrel for task, conversation, message, and task-manager protocol descriptors.
 */
export type { ConversationId, MessageId, TaskId } from "./methods.js";

export * from "./capabilities/index.js";

export {
  TaskClosedError,
  ConversationArchivedError,
  ConversationFullError,
  HookBlockedError,
  // Spec D1 (#598) — new tagged error for `task/conversation/*`
  // participant invariant.
  ParticipantNotAdmittedError,
  ConversationsCreate,
  ConversationsList,
  ConversationsGet,
  ConversationsUpdate,
  ConversationsMute,
  ConversationsUnmute,
  ConversationsAddParticipant,
  ConversationsRemoveParticipant,
  ConversationsLeave,
  ConversationsArchive,
  ConversationsUnarchive,
  MessagesSend,
  MessagesList,
  TasksCreate,
  TasksGet,
  TasksList,
  TasksClose,
  TasksCreateConversation,
  TasksCloseConversation,
  TasksAddParticipant,
  TasksRemoveParticipant,
  TasksStoreMessage,
  TasksGetMessages,
  TasksGetMessagesSince,
  // Spec D1 — additive `task/*` + `task/conversation/*` family.
  AppId,
  DEFAULT_APP_ID,
  inferConversationType,
  TaskCreate,
  TaskLeave,
  TaskConversationCreate,
  TaskConversationList,
  TaskConversationArchive,
  TaskConversationUnarchive,
  TaskConversationAddParticipant,
  TaskConversationRemoveParticipant,
  ConversationCreatedNotificationDefinition,
  ConversationUpdatedNotificationDefinition,
  ConversationArchivedNotificationDefinition,
  ConversationUnarchivedNotificationDefinition,
  ParticipantsAddedNotificationDefinition,
  ParticipantsRemovedNotificationDefinition,
  MessageReceivedNotificationDefinition,
  TaskClosedNotificationDefinition,
  TaskFailedNotificationDefinition,
  // Spec D1 — `task/conversation/*` notifications.
  TaskConversationCreatedNotificationDefinition,
  TaskConversationArchivedNotificationDefinition,
  TaskConversationUnarchivedNotificationDefinition,
  TaskConversationParticipantsAddedNotificationDefinition,
  TaskConversationParticipantsRemovedNotificationDefinition,
  validateTmDecision,
  tmDecisionSchema,
  messageWithTmDecisionSchema,
  // Spec D3 R11 — per-kind catalog subsets.
  nonTmAuthorityTaskRpcMethods,
  tmOnlyTaskRpcMethods,
} from "./methods.js";

export type {
  LogicalClock,
  Part,
  Message,
  Conversation,
  ConversationParticipant,
  ConversationSummary,
  TaskStatus,
  Task,
  TaskParticipant,
  TmType,
  ConversationCreatedNotification,
  ConversationUpdatedNotification,
  ConversationArchivedNotification,
  ConversationUnarchivedNotification,
  ParticipantsAddedNotification,
  ParticipantsRemovedNotification,
  MessageReceivedNotification,
  TmDecision,
  MessageWithTmDecision,
  // Spec D1 surface types.
  InitialConversationInput,
  TaskConversationListItem,
  TaskConversationCreatedNotification,
  TaskConversationArchivedNotification,
  TaskConversationUnarchivedNotification,
  TaskConversationParticipantsAddedNotification,
  TaskConversationParticipantsRemovedNotification,
} from "./methods.js";
