/** @file Package-private facade for the complete Client protocol representation. */

/* eslint-disable jsdoc/require-jsdoc -- Re-exported private representation symbols retain their owning-module documentation. */

export {
  ClientRepresentationError,
  decodeCanonical,
  encodeCanonical,
} from "./representation-canonical.js";
export {
  compareAgentIds,
  decodeDirectPacket,
  type DecodedOuterBody,
  decodeEvidenceMessage,
  decodeOuterBody,
  deriveEvidenceMessageId,
  encodeAction,
  fingerprintReply,
  hashActionCertificate,
  hashActionCertifiedRecord,
  hashAnchor,
  hashBeginMessage,
  hashContent,
  hashMembership,
  makeActionBinding,
  type OuterMembership,
  signEvidenceMessage,
  signOuterBody,
  signOuterEvidence,
  signOuterPacket,
} from "./representation-codec.js";
export {
  AckStatement,
  Action,
  ActionBinding,
  ActionCertificate,
  ActionCertifiedRecord,
  ActionHash,
  ActionSignatureStatement,
  AnchorHash,
  Begin,
  BeginDigest,
  CatchUpAttestation,
  CatchUpIncomplete,
  CatchUpItem,
  CatchUpPage,
  CatchUpRequest,
  CertifiedRecord,
  CompletedReanchor,
  Content,
  ContentHash,
  DirectPacket,
  DurabilityVoteStatement,
  EvidenceStatement,
  GenesisAnchor,
  JsonValueSchema,
  maximumContentBytes,
  maximumMembers,
  Membership,
  MembershipHash,
  MulticastAction,
  MulticastProposal,
  ReanchorBody,
  ReanchorVoteStatement,
  RecordHash,
  ReplyFingerprint,
  ReplyInput,
  StartAction,
  StartProposal,
} from "./representation-schemas.js";
export {
  durabilityThreshold,
  memberCard,
  type VerifiedActionCertifiedRecord,
  type VerifiedMembership,
  verifyActionCertificate,
  verifyActionCertifiedRecord,
  verifyCatchUpIncomplete,
  verifyCatchUpPage,
  verifyCertifiedRecord,
  verifyCompletedReanchor,
  verifyMembership,
  verifyOuterMessage,
  verifyStableEvidence,
  verifyStartProposal,
} from "./representation-verification.js";

/* eslint-enable jsdoc/require-jsdoc -- Restore package documentation rules. */
