/** @file Package-private facade for the complete Client protocol representation. */

/* eslint-disable jsdoc/require-jsdoc -- Re-exported private symbols retain their owning-module documentation. */

export {
  ClientRepresentationError,
  decodeCanonical,
  encodeCanonical,
} from "./representation-canonical.js";
export {
  compareAgentIds,
  decodeDirectPacket,
  type DecodedOuterBody,
  decodeEvidenceMessage,
  decodeOuterBody,
  deriveConversationId,
  deriveEvidenceMessageId,
  encodeActionCore,
  hashAction,
  hashAnchor,
  hashMembershipDescriptor,
  hashPostIntent,
  hashRecord,
  mintPostId,
  type OuterMembership,
  signEvidenceMessage,
  signOuterEvidence,
  signOuterPacket,
} from "./representation-codec.js";
export {
  ActionCertificate,
  ActionCertifiedRecord,
  ActionCore,
  ActionHash,
  ActionProposal,
  ActionSignatureStatement,
  AnchorBody,
  AnchorHash,
  CatchUpAttestationStatement,
  CatchUpIncomplete,
  CatchUpItem,
  CatchUpPage,
  CatchUpRequest,
  CertifiedRecord,
  CompletedReanchor,
  Content,
  ConversationId,
  ConversationIdentityInput,
  DirectPacket,
  DurabilityCertificate,
  DurabilityVoteStatement,
  EvidenceStatement,
  GenesisActionCore,
  GenesisAnchorBody,
  maximumContentBytes,
  maximumMembers,
  MembershipDescriptor,
  MembershipHash,
  PostActionCore,
  PostIntent,
  PostIntentHash,
  ReanchorBody,
  ReanchorCertificate,
  ReanchorVoteStatement,
  RecordCore,
  RecordHash,
  RouterAnchor,
} from "./representation-schemas.js";
export {
  memberCard,
  quorumThreshold,
  type VerifiedActionCertifiedRecord,
  type VerifiedActionCore,
  type VerifiedEvidence,
  type VerifiedMembership,
  type VerifiedRecordCore,
  verifyActionCertificate,
  verifyActionCertifiedRecord,
  verifyActionCore,
  verifyActionProposal,
  verifyCatchUpIncomplete,
  verifyCatchUpPage,
  verifyCertifiedRecord,
  verifyCompletedReanchor,
  verifyMembershipDescriptor,
  verifyOuterMessage,
  verifyRecordCore,
  verifyStableEvidence,
} from "./representation-verification.js";

/* eslint-enable jsdoc/require-jsdoc -- Restore package documentation rules. */
