apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: {{ .Values.resourceFlavor.name }}
spec:
  nodeLabels:
    {{ .Values.agentPool.label.key }}: {{ .Values.agentPool.label.value | quote }}
  nodeTaints:
    - key: {{ .Values.agentPool.taint.key }}
      value: {{ .Values.agentPool.taint.value | quote }}
      effect: {{ .Values.agentPool.taint.effect }}
  tolerations:
    - key: {{ .Values.agentPool.taint.key }}
      operator: Equal
      value: {{ .Values.agentPool.taint.value | quote }}
      effect: {{ .Values.agentPool.taint.effect }}
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: {{ .Values.clusterQueue.name }}
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
        - ephemeral-storage
      flavors:
        - name: {{ .Values.resourceFlavor.name }}
          resources:
            - name: cpu
              nominalQuota: {{ .Values.quota.cpu | quote }}
            - name: memory
              nominalQuota: {{ .Values.quota.memory }}
            - name: ephemeral-storage
              nominalQuota: {{ .Values.quota.ephemeralStorage }}
